pipeline {
    agent any
     parameters {
        string(defaultValue: "", description: 'What environment?', name: 'Environment')
        // choices are newline separated
        choice(choices: 'US-EAST-1\nUS-WEST-2', description: 'What AWS region?', name: 'region')
    }
    tools {
        maven 'Maven'
        jdk 'JAVA_HOME'
    }
    stages 
    {
        stage ('Checkout')
        {
            steps 
            {
                git (
                    url: 'https://github.com/vijaysingaran/DevOpsDemo',
                    credentialsId: 'ee4cdcc7-28e8-4e0d-a1b2-8e5775e8d115'
                )
            }
            
        }
    }
}